# Generated by Django 5.0.1 on 2024-01-22 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(limit_choices_to={'name__in': ()}, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app1.category'),
        ),
    ]
