# Generated by Django 5.0.1 on 2024-01-22 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_brand_color_size_alter_subcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(limit_choices_to={'name__in': ()}, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='app1.category'),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Men'), ('W', 'Women'), ('B', 'Both')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(limit_choices_to={'name__in': ()}, on_delete=django.db.models.deletion.CASCADE, to='app1.brand')),
                ('size', models.ForeignKey(limit_choices_to={'name__in': ()}, on_delete=django.db.models.deletion.CASCADE, to='app1.size')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.subcategory')),
            ],
        ),
    ]
